name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3.0.0
      with:
        go-version: 1.18.0-rc.1
    - name: Build Windows
      env:
        GOOS: windows
        GOARCH: amd64
      run: go build -o auth-server.exe . && go build -o ./LoginNotify/LoginNotify.exe ./LoginNotify
    - name: Build Linux
      env:
        GOOS: linux
        GOARCH: amd64
      run: go build -o auth-server . && go build -o ./LoginNotify/LoginNotify ./LoginNotify
    - name: Upload a Windows Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        name: linux-build.zip
        path: auth-server
    - name: Upload a Windows Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        name: linux-build-notify.zip
        path: LoginNotify/LoginNotify
    - name: Upload a Linux Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        name: windows-build
        path: auth-server.exe
    - name: Upload a Windows Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        name: windows-build
        path: LoginNotify/LoginNotify.exe
